import {
  LearnerProfile,
  RoleMatch,
  RoadmapMilestone,
  AssessmentQuestion,
  AssessmentResult,
  CommunityPost,
  RewardItem,
  LeaderboardEntry,
  CertificateData,
} from "@/types/trailmark";

export const initialLearnerProfile: LearnerProfile = {
  id: "scholar-ev-1048",
  name: "Eleanor Vance",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  currentRole: "Senior Marketing Analytics Manager",
  targetRole: "AI Engineer",
  targetTimelineMonths: 18,
  persona: "digger",
  scholarLevel: "Academic Scholar Level IV",
  joinedDate: "Sept 2023",
  totalPoints: 1240,
  streakDays: 5,
  completedMilestoneIds: ["ms-01"],
  currentModuleId: "mod-02-01",
  weeklyGoalHours: 12,
  hoursCompletedThisWeek: 8.5,
  bio: "Pursuing rigorous mathematical intuition and production neural architecture design. Focused on generative systems and multi-task loss optimization.",
};

export const initialRoleMatches: RoleMatch[] = [
  {
    id: "ai-engineer",
    title: "AI Engineer",
    matchPercentage: 89,
    salaryRange: "$165k - $210k",
    tag: "Top Match",
    summary:
      "Your strong foundation in statistical modeling and Python perfectly aligns with the analytical demands of machine learning systems. Bridge the gap into tensor calculus and deep neural pipelines.",
    alignmentReason: "High synergy with existing predictive analytics; requires deep learning foundations and distributed training experience.",
    skills: [
      { name: "Statistical Modeling", matchScore: 92, status: "strong" },
      { name: "Python & Data Wrangling", matchScore: 88, status: "strong" },
      { name: "Neural Network Architectures", matchScore: 68, status: "gap" },
      { name: "Backpropagation & Optimizers", matchScore: 62, status: "gap" },
      { name: "MLOps & Tensor Serving", matchScore: 45, status: "gap" },
    ],
    milestonesCount: 4,
    estTimeToMastery: "14 - 18 Months",
    primaryDomain: "AI Engineering",
  },
  {
    id: "data-analytics-lead",
    title: "Data Analytics Lead",
    matchPercentage: 78,
    salaryRange: "$150k - $185k",
    tag: "Strategic Pivot",
    summary:
      "Leverage your management seniority and business intelligence intuition to direct large-scale data engineering and analytics pods.",
    alignmentReason: "Fastest transition timeline with immediate managerial leadership parity.",
    skills: [
      { name: "Analytics Strategy", matchScore: 95, status: "strong" },
      { name: "Executive Synthesis", matchScore: 90, status: "strong" },
      { name: "SQL & Data Warehousing", matchScore: 82, status: "strong" },
      { name: "Distributed Spark Pipelines", matchScore: 50, status: "gap" },
    ],
    milestonesCount: 3,
    estTimeToMastery: "6 - 9 Months",
    primaryDomain: "Business Intelligence",
  },
  {
    id: "ml-product-manager",
    title: "Machine Learning Product Manager",
    matchPercentage: 64,
    salaryRange: "$160k - $195k",
    tag: "High Growth",
    summary:
      "Combine marketing domain fluency with AI system feasibility evaluation to lead productization of LLM and computer vision features.",
    alignmentReason: "Focuses on AI capability boundaries, safety guardrails, and customer value capture.",
    skills: [
      { name: "Product Discovery", matchScore: 85, status: "strong" },
      { name: "Stakeholder Alignment", matchScore: 90, status: "strong" },
      { name: "Model Evaluation Metrics", matchScore: 55, status: "gap" },
      { name: "Technical Feasibility Assessment", matchScore: 48, status: "gap" },
    ],
    milestonesCount: 3,
    estTimeToMastery: "8 - 12 Months",
    primaryDomain: "AI Product Management",
  },
];

export const initialRoadmapMilestones: RoadmapMilestone[] = [
  {
    id: "ms-01",
    number: 1,
    title: "Mathematics for Machine Learning",
    description: "Linear algebra, multivariable calculus, matrix decompositions, and probability theory essentials.",
    status: "completed",
    completedDate: "Oct 12",
    estimatedHours: 40,
    badgeTitle: "Foundations Certified",
    modules: [
      { id: "m1-1", title: "Vector Spaces & Matrix Transformations", type: "concept", duration: "6 hrs", completed: true },
      { id: "m1-2", title: "Gradient Vectors & Jacobian Matrices", type: "concept", duration: "8 hrs", completed: true },
      { id: "m1-3", title: "Probability Distributions & Bayes Theorem", type: "lab", duration: "10 hrs", completed: true },
      { id: "m1-4", title: "Foundations Milestone Assessment", type: "assessment", duration: "2 hrs", completed: true },
    ],
    diggerDeepDive: {
      readingList: [
        "Strang, G. — Linear Algebra and Learning from Data (Ch. 1-3)",
        "Deisenroth, M. P. — Mathematics for Machine Learning",
      ],
      academicPapers: [
        "A Singular Value Decomposition Primer for Neural Operators",
      ],
      theoreticalFoundation: "Rigorous eigenvalue formulation and gradient flow topology in n-dimensional manifolds.",
    },
    surfaceSummary: [
      "Mastered 2D/3D matrix transforms and dot products.",
      "Understood how partial derivatives compute error slopes.",
      "Acquired probability density functions intuition.",
    ],
  },
  {
    id: "ms-02",
    number: 2,
    title: "Deep Learning Foundations & Architectures",
    description: "Multi-layer perceptrons, backpropagation mechanics, activation dynamics, and regularization methods.",
    status: "in_progress",
    estimatedHours: 55,
    badgeTitle: "Architecture Apprentice",
    modules: [
      {
        id: "mod-02-01",
        title: "Vanishing Gradients & Activation Functions",
        type: "concept",
        duration: "5 hrs",
        completed: false,
        diggerNotes: "Examines saturation regions in Sigmoid/Tanh versus piecewise linearity in ReLU and GELU variants.",
        citations: ["Glorot & Bengio (2010): Understanding difficulty of training deep feedforward neural networks"],
      },
      {
        id: "mod-02-02",
        title: "Backpropagation from Scratch in NumPy",
        type: "lab",
        duration: "12 hrs",
        completed: false,
      },
      {
        id: "mod-02-03",
        title: "Stochastic Optimizers (AdamW, RMSprop, Lion)",
        type: "concept",
        duration: "6 hrs",
        completed: false,
      },
      {
        id: "mod-02-04",
        title: "Adaptive Architecture Milestone Exam",
        type: "assessment",
        duration: "3 hrs",
        completed: false,
      },
    ],
    diggerDeepDive: {
      readingList: [
        "Goodfellow, Bengio, Courville — Deep Learning (MIT Press)",
        "Bishop, C. — Pattern Recognition and Machine Learning",
      ],
      academicPapers: [
        "He et al. (2015) — Delving Deep into Rectifiers: Surpassing Human-Level Performance",
        "Loshchilov & Hutter (2019) — Decoupled Weight Decay Regularization (AdamW)",
      ],
      theoreticalFoundation: "Non-convex optimization landscapes, saddle points avoidance, and spectral radius of weight tensors.",
    },
    surfaceSummary: [
      "Why ReLU stops gradients from dying compared to Sigmoid.",
      "How chain rule sends error signals backward through nodes.",
      "Hands-on intuition for learning rates and momentum.",
    ],
  },
  {
    id: "ms-03",
    number: 3,
    title: "Sequence Models & Transformer Mechanics",
    description: "Self-attention mechanisms, multi-head projections, positional encodings, and encoder-decoder stacks.",
    status: "locked",
    estimatedHours: 65,
    badgeTitle: "Attention Master",
    modules: [
      { id: "m3-1", title: "Recurrent Networks to Scaled Dot-Product Attention", type: "concept", duration: "8 hrs", completed: false },
      { id: "m3-2", title: "Multi-Head Attention & KV Cache Implementation", type: "lab", duration: "16 hrs", completed: false },
      { id: "m3-3", title: "Rotary Embeddings (RoPE) and Context Extensions", type: "concept", duration: "8 hrs", completed: false },
      { id: "m3-4", title: "Transformer Benchmark Capstone", type: "project", duration: "20 hrs", completed: false },
    ],
    diggerDeepDive: {
      readingList: ["Vaswani et al. — Attention Is All You Need", "Su et al. — RoFormer: Enhanced Transformer with Rotary Position Embedding"],
      academicPapers: ["FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness"],
      theoreticalFoundation: "Quadratic complexity in attention matrices, GPU SRAM tiling, and softmax numerical stability.",
    },
    surfaceSummary: [
      "How queries, keys, and values look up relevant words in context.",
      "Why transformers parallelize training better than RNNs.",
      "Practical prompt encoding structures.",
    ],
  },
  {
    id: "ms-04",
    number: 4,
    title: "Production ML Systems & Distributed Serving",
    description: "Quantization (AWQ/GPTQ), vLLM deployment, continuous batching, and observability pipelines.",
    status: "locked",
    estimatedHours: 50,
    badgeTitle: "Production Engineer",
    modules: [
      { id: "m4-1", title: "Model Quantization & FP8/INT4 Precision Tradeoffs", type: "concept", duration: "8 hrs", completed: false },
      { id: "m4-2", title: "High-Throughput Serving with vLLM & PagedAttention", type: "lab", duration: "14 hrs", completed: false },
      { id: "m4-3", title: "End-to-End Capstone Defense & Certification Exam", type: "assessment", duration: "4 hrs", completed: false },
    ],
    diggerDeepDive: {
      readingList: ["Kwon et al. — Efficient Memory Management for Large Language Model Serving with PagedAttention"],
      academicPapers: ["Dettmers et al. — QLoRA: Efficient Finetuning of Quantized LLMs"],
      theoreticalFoundation: "Memory bandwidth bottlenecks vs compute bound operations in speculative decoding.",
    },
    surfaceSummary: [
      "Running LLMs on smaller memory footprints.",
      "Serving hundreds of concurrent queries efficiently.",
      "Monitoring drift and latency in production.",
    ],
  },
];

export const adaptiveAssessmentQuestions: AssessmentQuestion[] = [
  {
    id: "q-01",
    questionNumber: 1,
    totalQuestions: 5,
    level: "Intermediate",
    prompt: "Which activation function is most commonly used in the hidden layers of deep neural networks to mitigate the vanishing gradient problem?",
    codeSnippet: `def forward_pass(x, W, b):\n    z = np.dot(x, W) + b\n    # Activation step\n    return activation(z)`,
    options: [
      { id: "opt-1", text: "Sigmoid" },
      { id: "opt-2", text: "Tanh" },
      { id: "opt-3", text: "ReLU (Rectified Linear Unit)" },
      { id: "opt-4", text: "Softmax" },
    ],
    correctOptionId: "opt-3",
    explanation: "ReLU is the most common choice as it outputs the input directly if it is positive (gradient is 1), otherwise it outputs zero. This constant derivative for positive activations prevents gradients from diminishing exponentially across deep layers.",
    citation: "Glorot, X., & Bengio, Y. (2010). Understanding the difficulty of training deep feedforward neural networks. AISTATS.",
    conceptTag: "Vanishing Gradients",
  },
  {
    id: "q-02",
    questionNumber: 2,
    totalQuestions: 5,
    level: "Intermediate",
    prompt: "In backpropagation, how is the gradient of the loss with respect to an early layer weight computed?",
    options: [
      { id: "opt-1", text: "By numerically taking finite differences at every training iteration" },
      { id: "opt-2", text: "By applying the chain rule of calculus backward from the output layer to the early layer" },
      { id: "opt-3", text: "By taking the direct determinant of the weight matrix without loss reference" },
      { id: "opt-4", text: "By randomly permuting weight vectors until loss converges" },
    ],
    correctOptionId: "opt-2",
    explanation: "Backpropagation applies the multivariate chain rule systematically from the output loss through intermediate layer Jacobian matrices to calculate exact analytical gradients efficiently.",
    citation: "Rumelhart, D. E., Hinton, G. E., & Williams, R. J. (1986). Learning representations by back-propagating errors. Nature, 323(6088).",
    conceptTag: "Chain Rule",
  },
  {
    id: "q-03",
    questionNumber: 3,
    totalQuestions: 5,
    level: "Advanced",
    prompt: "Why does decoupled weight decay (AdamW) outperform standard L2 regularization in adaptive gradient optimizers like Adam?",
    options: [
      { id: "opt-1", text: "Standard L2 regularization scales the decay by the inverse second moment, decaying high-frequency weights less than intended" },
      { id: "opt-2", text: "AdamW completely disables gradient momentum during backpropagation" },
      { id: "opt-3", text: "Standard L2 regularization doubles the memory footprint of optimizer states" },
      { id: "opt-4", text: "AdamW replaces floating point weights with integer approximations" },
    ],
    correctOptionId: "opt-1",
    explanation: "In standard Adam with L2 regularization, the penalty gradient is added directly to the gradient vector before dividing by sqrt(v_t). Weights with large historical gradients experience less relative decay. AdamW decouples weight decay from the gradient update step.",
    citation: "Loshchilov, I., & Hutter, F. (2019). Decoupled Weight Decay Regularization. ICLR 2019.",
    conceptTag: "Adaptive Optimization",
  },
  {
    id: "q-04",
    questionNumber: 4,
    totalQuestions: 5,
    level: "Intermediate",
    prompt: "What is the primary computational bottleneck of standard scaled dot-product attention in Transformer architectures as context length N grows?",
    options: [
      { id: "opt-1", text: "Linear O(N) memory scaling in feedforward linear projections" },
      { id: "opt-2", text: "Quadratic O(N^2) memory and compute complexity in calculating the N x N attention matrix" },
      { id: "opt-3", text: "Exponential O(2^N) depth complexity in layer normalization" },
      { id: "opt-4", text: "Constant O(1) latency regardless of context length" },
    ],
    correctOptionId: "opt-2",
    explanation: "Computing QK^T requires materializing an N x N matrix of attention weights between all token pairs, causing quadratic growth in both GPU memory footprint and arithmetic operations.",
    citation: "Vaswani, A., et al. (2017). Attention Is All You Need. NeurIPS.",
    conceptTag: "Attention Complexity",
  },
  {
    id: "q-05",
    questionNumber: 5,
    totalQuestions: 5,
    level: "Advanced",
    prompt: "How does FlashAttention achieve a 2x-4x speedup over standard attention without modifying mathematical outputs?",
    options: [
      { id: "opt-1", text: "By pruning 75% of query-key pairs using random sampling" },
      { id: "opt-2", text: "By tiling the softmax calculation into blocks that fit within fast GPU SRAM, avoiding slow HBM read/write roundtrips" },
      { id: "opt-3", text: "By converting all weights to 1-bit representations during runtime" },
      { id: "opt-4", text: "By evaluating attention only on every fourth layer" },
    ],
    correctOptionId: "opt-2",
    explanation: "FlashAttention uses online softmax scaling to compute attention in small tiles loaded directly into GPU fast SRAM, eliminating redundant high-bandwidth memory (HBM) IO traffic.",
    citation: "Dao, T., et al. (2022). FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness. NeurIPS.",
    conceptTag: "GPU Memory Hierarchy",
  },
];

export const sampleAssessmentResult: AssessmentResult = {
  id: "res-dl-92",
  topic: "Deep Learning Fundamentals & Optimization",
  scorePercentage: 92,
  correctCount: 5,
  totalQuestions: 5,
  timeSpentMinutes: 8,
  speedComparison: "15% faster than cohort average",
  passed: true,
  strengths: [
    "Flawless application of chain-rule calculations across multi-layer graphs.",
    "Precise conceptual differentiation between AdamW decoupled decay and standard L2 regularization.",
    "Comprehensive grasp of GPU memory bottlenecks in quadratic attention mechanics.",
  ],
  areasForRefinement: [
    "Review continuous batching edge-cases in asynchronous KV-cache eviction policies.",
  ],
  trailGuideNote:
    "Your grasp on Backpropagation algorithms was exceptional. You completed complex gradient flow proofs with outstanding accuracy and speed. You are cleared for Advanced Sequence Modeling.",
  certificationEligible: true,
  awardedPoints: 250,
};

export const initialCommunityPosts: CommunityPost[] = [
  {
    id: "post-01",
    author: {
      name: "Alex Chen",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
      role: "AI Engineering Fellow",
      scholarLevel: "Level III Scholar",
    },
    timestamp: "2 hours ago",
    domainTag: "AI_Engineering",
    title: "How do I optimize this multi-task loss function without gradient collapse?",
    content:
      "I'm struggling with a custom loss function for a multi-task learning model combining contrastive embedding and classification loss. The gradients for the auxiliary head seem to vanish early on. Has anyone dealt with balancing MSE and Cross-Entropy dynamically?",
    codeSnippet: `def custom_multi_loss(y_true, y_pred, alpha=0.3):\n    loss_cls = cross_entropy(y_true['cls'], y_pred['cls'])\n    loss_embed = contrastive_loss(y_true['embed'], y_pred['embed'])\n    return loss_cls + (alpha * loss_embed)`,
    upvotes: 24,
    repliesCount: 7,
    isHelpfulAnswered: true,
    answers: [
      {
        id: "ans-01",
        author: {
          name: "Elena Rostova",
          avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
          role: "Doctoral Researcher",
          badge: "Top Contributor",
        },
        timestamp: "1 hour ago",
        content:
          "Consider using GradNorm (Chen et al., 2018). Instead of a static alpha scalar, normalize the gradient norms dynamically by balancing the pace at which each task loss decreases. Here is the gradient scaling formula we used in our transformer ablation study.",
        upvotes: 18,
        isAccepted: true,
      },
    ],
    tags: ["Loss Functions", "Multi-Task", "PyTorch"],
  },
  {
    id: "post-02",
    author: {
      name: "Julian Thorne",
      avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
      role: "Systems Architect",
      scholarLevel: "Level V Scholar",
    },
    timestamp: "4 hours ago",
    domainTag: "Production_ML",
    title: "Benchmarking vLLM PagedAttention vs TensorRT-LLM on Llama 3 70B",
    content:
      "Just finished compiling our inference throughput benchmarks. PagedAttention shows a 3.2x throughput improvement during heavy concurrent prefix-caching workloads. Sharing full latency distribution plots and CUDA kernel profiles.",
    upvotes: 42,
    repliesCount: 12,
    isHelpfulAnswered: false,
    tags: ["Inference", "vLLM", "CUDA"],
  },
  {
    id: "post-03",
    author: {
      name: "Marcus Aurelius Vance",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      role: "Research Scholar",
      scholarLevel: "Level IV Scholar",
    },
    timestamp: "1 day ago",
    domainTag: "Mathematics",
    title: "Intuition behind SVD and low-rank adapter approximations (LoRA)",
    content:
      "When breaking down weight matrix update ΔW into B * A (where rank r << d), why does maintaining rank 8 or 16 capture over 90% of expressive gradient subspace? Let's discuss singular value spectra.",
    upvotes: 38,
    repliesCount: 9,
    isHelpfulAnswered: true,
    tags: ["Linear Algebra", "LoRA", "SVD"],
  },
];

export const initialRewardItems: RewardItem[] = [
  {
    id: "rew-01",
    title: "Institutional Newsletter Spotlight",
    category: "Recognition",
    pointCost: 800,
    icon: "newspaper",
    description: "Secure a featured research profile in the monthly Trailmark Academic Digest sent to 15,000+ engineers and research faculty.",
    available: true,
    redeemed: false,
  },
  {
    id: "rew-02",
    title: "1-on-1 AI Architecture Critique",
    category: "Mentorship",
    pointCost: 1200,
    icon: "school",
    description: "45-minute private session with a Principal AI Scientist to review your capstone repository and mathematical derivations.",
    available: true,
    redeemed: false,
  },
  {
    id: "rew-03",
    title: "Academic ACM Digital Library Access Pass",
    category: "Resource",
    pointCost: 500,
    icon: "library_books",
    description: "Quarterly institutional access token for peer-reviewed machine learning proceedings and journal archives.",
    available: true,
    redeemed: true,
  },
  {
    id: "rew-04",
    title: "Distinguished Scholar Profile Seal",
    category: "Badge",
    pointCost: 350,
    icon: "verified",
    description: "Permanent golden badge and verified credentials watermark displayed on your public Trailmark portfolio and transcript.",
    available: true,
    redeemed: false,
  },
];

export const initialLeaderboardEntries: LeaderboardEntry[] = [
  {
    rank: 1,
    name: "Dr. Sanjay Patel",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    domain: "Neural Architectures",
    points: 2480,
    streakDays: 42,
    badge: "Grandmaster Scholar",
    change: "same",
  },
  {
    rank: 2,
    name: "Elena Rostova",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    domain: "Applied Physics & ML",
    points: 2140,
    streakDays: 28,
    badge: "Master Theorist",
    change: "up",
  },
  {
    rank: 3,
    name: "Julian Thorne",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    domain: "Distributed Systems",
    points: 1950,
    streakDays: 19,
    badge: "Senior Fellow",
    change: "down",
  },
  {
    rank: 4,
    name: "Eleanor Vance",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    domain: "AI Engineering",
    points: 1240,
    streakDays: 5,
    badge: "Academic Scholar IV",
    isCurrentUser: true,
    change: "up",
  },
  {
    rank: 5,
    name: "Marcus Aurelius Vance",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    domain: "Statistical Mechanics",
    points: 1180,
    streakDays: 14,
    badge: "Scholar IV",
    change: "same",
  },
];

export const sampleCertificate: CertificateData = {
  id: "cert-trail-2024-8842",
  certificateNumber: "TM-2024-AI-88429",
  recipientName: "Eleanor Vance",
  recipientTitle: "Candidate for AI Systems Specialist",
  pathTitle: "Deep Learning Foundations & Neural Architectures",
  completionDate: "October 24, 2024",
  grade: "Distinction (92% Mastery)",
  verifiedCompetencies: [
    "Multivariable Gradient Flow & Tensor Calculus",
    "Backpropagation Derivations & Custom Loss Optimization",
    "Non-linear Activation Dynamics (ReLU, GELU, SwiGLU)",
    "Adaptive Optimizers (AdamW, RMSprop) & Momentum Mechanics",
    "Empirical Neural Network Regularization & Normalization",
  ],
  issuer: "Trailmark Academic Council & AI Institute",
  verificationHash: "0x7F8B2C4E9A1D6E3F...892A",
  honorsDistinction: "Highest Distinction for Exceptional Theoretical Rigor",
};
